export const campus = {
  theme: "campus-theme",
  kicker: "Full EMIS Suite · Universities & Colleges",
  title: "EduRole Campus",
  description: "A comprehensive education management platform for universities, colleges and professional bodies — cloud-hosted or on-premise.",
  stats: [["700M+", "Kwacha collected in 2024"], ["1M+", "Students served"], ["57+", "Institutions"], ["125+", "Available modules"]],
  sectionLabel: "Complete university platform",
  sectionTitle: "Every operation. One connected system.",
  sectionText: "EduRole Campus covers the entire student lifecycle and every operational function of a higher-education institution.",
  features: [
    { label: "Student lifecycle", title: "Online Admissions", text: "Manage the entire application lifecycle from a digital portal. Automated eligibility checks, document uploads, shortlisting, conditional offers and final enrolment — all paperless." },
    { label: "Academic", title: "Programme & Faculty Management", text: "Manage faculties, departments, programmes, courses and modules. Define entry requirements, credit frameworks and academic calendars for each programme." },
    { label: "Finance", title: "Finance Module", text: "Automate bank payment reconciliation, manage complex fee structures across programmes, and integrate with Sage, Microsoft Navision or national financial management systems." },
    { label: "Academic", title: "Grades, Exams & Transcripts", text: "Full gradebook with secure online and offline exam administration, automated result processing, exam-board workflows, and one-click official transcripts and certificates." },
    { label: "HR", title: "Human Resources", text: "Comprehensive staff management: profiles, KPIs, performance appraisals, contract management, leave requests, payroll integration and complete HR workflow automation." },
    { label: "Operations", title: "Accommodation Management", text: "Room allocation and housing application management. Track room availability, process housing payments, manage maintenance requests and residential compliance." },
    { label: "Integration", title: "Library Integration (Koha)", text: "Students access catalogues, manage borrowing and view fines through the EduRole student portal with full Koha integration." },
    { label: "Integration", title: "Moodle LMS Integration", text: "Single sign-on lets students access classes, assignments and grades across EduRole and Moodle with one account." },
    { label: "Security", title: "LDAP & Single Sign-On", text: "Use one set of credentials across EduRole, Moodle, Koha, email and connected systems through LDAP and SSO." },
    { label: "Operations", title: "Infrastructure Management", text: "Manage campus buildings, lecture halls and facilities. Track maintenance, seating capacity, bookings and compliance from one dashboard." },
    { label: "Analytics", title: "Advanced Analytics & EMIS", text: "Real-time dashboards across every module with standard reports, custom interactive dashboards and national-level EMIS aggregation." },
    { label: "Enterprise", title: "Multi-Institution Management", text: "Manage multiple campuses, faculties or institutions from a single portal — ideal for regulators, accreditation bodies and professional organisations." },
  ],
  spotlights: [
    {
      id: "learning",
      label: "eLearning & eLibrary",
      title: "Teaching & learning, built in.",
      text: "EduRole Campus ships with a full eLearning environment and digital eLibrary, so students learn, borrow and submit without leaving the platform.",
      items: [
        ["Inbuilt eLearning", "Courses, lessons, assignments, quizzes and grades, with optional Moodle interoperability."],
        ["Digital eLibrary", "A searchable catalogue of e-books, journals and course resources integrated with Koha."],
        ["One sign-on", "Students and lecturers move between Campus, eLearning and the eLibrary with one LDAP / SSO login."],
      ],
    },
    {
      id: "ai",
      label: "AI-assisted course building",
      title: "Build courses with a private, self-hosted AI.",
      text: "Lecturers can turn their own notes, slides, PDFs and past papers into structured lessons, quizzes and summaries. The model runs on the institution’s infrastructure, so student and research data never leaves campus.",
      items: [
        ["Dynamic course building", "Generate outlines, lessons, assessments and summaries from existing teaching materials."],
        ["Self-hosted model", "Runs on your servers with no third-party AI cloud and no per-token fees."],
        ["Data sovereignty", "Student and research data stays fully under institutional control."],
        ["Works offline", "No dependence on external APIs — suitable for low-bandwidth campuses."],
      ],
    },
  ],
  options: {
    title: "Cloud or on-premise.",
    items: [
      { mark: "☁", title: "Cloud hosted", text: "We host and maintain EduRole on secure infrastructure.", points: ["Automatic updates and backups", "No server hardware required", "Scales with your institution"] },
      { mark: "⌂", title: "On-premise", text: "Run EduRole on your own servers with full data sovereignty.", points: ["Complete control of your data", "Works in low-bandwidth environments", "Efficient on modest hardware"] },
    ],
  },
  integrations: ["Sage", "Microsoft Navision", "Koha Library System", "Moodle LMS", "LDAP / Active Directory", "Google Workspace", "Bank Payment APIs", "National Financial Systems"],
  related: {
    label: "Managing a primary or secondary school?",
    title: "Try EduRole School",
    text: "Our cloud SaaS platform for primary and secondary schools is available instantly at cloud.edurole.com — with no installation or setup fees.",
    href: "/school",
    link: "See EduRole School",
  },
  cta: "Bring your whole institution together.",
};

export const school = {
  theme: "school-theme",
  kicker: "Cloud SaaS · Primary & Secondary",
  title: "EduRole School",
  description: "A complete cloud-based school management system. No servers and no installation — log in and start managing your school.",
  external: "https://cloud.edurole.com",
  stats: [["Cloud", "No installation needed"], ["Instant", "Set up in minutes"], ["Any device", "Mobile-friendly"], ["Affordable", "Built for African schools"]],
  sectionLabel: "Everything a school needs",
  sectionTitle: "Simple daily management.",
  sectionText: "Bring teachers, learners, parents, classes and finances into one easy-to-use school platform.",
  features: [
    { label: "Students", title: "Student Enrollment & Management", text: "Digital student records for enrolments, transfers and withdrawals, with guided workflows and spreadsheet imports." },
    { label: "Academic", title: "Class & Grade Management", text: "Create classes, assign teachers, manage academic grades and track progression across terms and years." },
    { label: "Operations", title: "Timetable Management", text: "Generate timetables with conflict detection and sync schedules to teachers’ mobile calendars." },
    { label: "Academic", title: "Grades & Assessments", text: "Capture assignments, tests and exams with automatic averages, rankings and national grading scales." },
    { label: "Finance", title: "Fee Management", text: "Define fee structures, record payments, generate receipts and track outstanding balances." },
    { label: "Operations", title: "Attendance Tracking", text: "Teachers record attendance from any device with reports and automated parent alerts." },
    { label: "People", title: "Teacher Management", text: "Manage profiles, subject assignments, timetable loads, qualifications and leave requests." },
    { label: "Community", title: "Parent Portal & Notifications", text: "Parents view grades, attendance, timetables and balances, supported by SMS and email notifications." },
    { label: "Reporting", title: "Report Cards & Transcripts", text: "Generate branded report cards and transcripts aligned with national standards." },
    { label: "Insights", title: "Analytics & Reporting", text: "Compare pass rates, attendance trends and fee collection across classes, subjects and periods." },
    { label: "Access", title: "Mobile Friendly & Cloud-Based", text: "Works across phones, tablets and computers with automatic updates and backups." },
  ],
  cta: "Start managing your school today.",
};

export const emis = {
  theme: "emis-theme",
  kicker: "National Scale · Ministries & Regulators",
  title: "One system for an entire sector.",
  description: "Manage every school, college or university from a single national portal, with real-time information from application to graduation.",
  stats: [["$250M+", "Processed in 2025"], ["1M+", "Students served"], ["57+", "Institutions connected"], ["3", "National portals"]],
  sectionLabel: "Built for national scale",
  sectionTitle: "The whole sector, on one screen.",
  sectionText: "Wherever many institutions report into one authority, EduRole EMIS provides one consistent source of information.",
  audiences: [
    ["Ministries of Education", "Oversee public and private institutions with live information for planning and policy."],
    ["TEVET & Sector Authorities", "Run technical and vocational providers with consistent enrolment, assessment and reporting."],
    ["Professional Bodies", "Manage registration, CPD, examinations and certification under one regulatory roof."],
    ["Higher-Education Regulators", "Accredit, monitor and aggregate standardised data from universities and colleges."],
  ],
  features: [
    { label: "Intelligence", title: "Advanced data analytics", text: "Monitor national indicators and build interactive dashboards across every institution." },
    { label: "Access", title: "One portal, all users", text: "Provide secure role-based access for students, institutions and national administrators." },
    { label: "Automation", title: "Paperless processes", text: "Capture reliable data as part of automated workflows instead of manual reporting." },
    { label: "National", title: "Multi-institution management", text: "Administer institutions, students and programmes through one national structure." },
    { label: "Operations", title: "Finance & infrastructure", text: "Manage payments, assets, maintenance, capacity and compliance at scale." },
    { label: "Academic", title: "Admissions, grades & exams", text: "Standardise the complete academic lifecycle across a sector." },
  ],
  cta: "Run your sector on one platform.",
};
